// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6aGkD5gsQTdGwvWVN7WGhpMxhCCwIvTE',
    appId: '1:83047941471:web:d793e703c068694271e2ea',
    messagingSenderId: '83047941471',
    projectId: 'project-eaf4c3fc-f24b-45b6-bab',
    authDomain: 'project-eaf4c3fc-f24b-45b6-bab.firebaseapp.com',
    storageBucket: 'project-eaf4c3fc-f24b-45b6-bab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCve3-0BoTU56fIIi5JseHyxz3_DixUDoM',
    appId: '1:83047941471:android:01c4eb5d01b920a071e2ea',
    messagingSenderId: '83047941471',
    projectId: 'project-eaf4c3fc-f24b-45b6-bab',
    storageBucket: 'project-eaf4c3fc-f24b-45b6-bab.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6aGkD5gsQTdGwvWVN7WGhpMxhCCwIvTE',
    appId: '1:83047941471:web:83d4d8f238dbd6d871e2ea',
    messagingSenderId: '83047941471',
    projectId: 'project-eaf4c3fc-f24b-45b6-bab',
    authDomain: 'project-eaf4c3fc-f24b-45b6-bab.firebaseapp.com',
    storageBucket: 'project-eaf4c3fc-f24b-45b6-bab.firebasestorage.app',
  );
}
